### ISSUE TITLE
Afficher la liste des villes disponibles

### ISSUE THREAD

**Issue by AntoineTrouche** [medialab/ScienceTrotterS_mobile#10]
Forccast fourni la liste des villes initialement présentes dans l'application (libellé + photos)
Seul l'affichage en mosaïque est retenu, il n'est pas nécessaire pour cette page de faire un affichage en mode "carte" comme cela a été proposé.

**Comment by NathalieSim** [comment]
![02-ville](https://user-images.githubusercontent.com/38243664/39195550-657e871e-47e0-11e8-8a5f-1fcf68f3fb45.jpg)
![02-ville-menu-1 2](https://user-images.githubusercontent.com/38243664/39195552-659fa462-47e0-11e8-93b5-77683bfd76d3.jpg)

**Comment by AntoineTrouche** [comment]
[BUG] "SÉLECTIONNEZ" est coupé (le Z ou le EZ est sur une seconde ligne) sur le smartphone testé. Est il possible d'adapter la police à la taille de l'écran si celui ci ne permet pas d'afficher "SÉLECTIONNEZ" sur une seule ligne avec la police de base ?
