### ISSUE TITLE
Questions SP - mobile

### ISSUE THREAD

**Issue by AntoineTrouche** [medialab/ScienceTrotterS_mobile#24]
https://github.com/medialab/ScienceTrotterS_mobile

- [ ] Compléter un README avec une description sommaire de la structure (mentionner Ionic par exemple) et la procédure de build.

- [ ] renseigner correctement le package.json : nom, auteur, home page, licence...

- [ ] prévoir de mettre l'URL de l'api dans un fichier de conf et non en dur dans le code

**Comment by AndreuFlorent** [comment]
C'est fait. On te laisse revenir vers nous si besoin,
