### ISSUE TITLE
Documentation pour compilation, test et déploiement de l'application

### ISSUE THREAD

**Issue by AntoineTrouche** [medialab/ScienceTrotterS_mobile#58]
Fournir une documentation précise pour la compilation, le test et le déploiement de l'application mobile.

**Comment by AndreuFlorent** [comment]
https://ionicframework.com/docs/v1/guide/publishing.html

**Comment by AntoineTrouche** [comment]
Publier la documentation dans le readme du dépot de l'application mobile, quitte à ce que soit pointé la documentation de ionic.
Est nécessaire dans le readme ce que TNG fait pour publier l'appli, même si cela correspond à la même chose que le document.
