### ISSUE TITLE
Questions API/Backoffice pour PPRD

### ISSUE THREAD

**Issue by AntoineTrouche** [medialab/ScienceTrotterS_mobile#62]
- les ingénieurs du Medialab ont corrigé des erreurs sur la configuration, merci de ne pas supprimer ces modifications (sauf si elles posent des problèmes, n'hésitez pas à me le faire remonter)
- il faudrait nous créer une clef d'api du service de cartographie
- il y a des fichiers bizarres dans le dossier database/builder qu'il faut corriger, détectés par l'alerte suivante : "Warning: Ambiguous class resolution, "Database\Builder\UpdateBuilder" was found in both "/api/database/builder/DefaultUpdater.php" and "/api/database/builder/UpdateBuilder.php", the first will be used."
-  à quoi servent les scripts update_database_v1.php et update_database_v2.php ?
- différentes version d'un même fichier co-existent dans Github avec des numéros de version dans le nom. Ce n'est pas clair, il faut les renommer pour clarifier la situation.
- la configuration du backoffice a été supprimée par un commit : https://github.com/medialab/ScienceTrotterS_backoffice/commit/e7b2b98f68121266d0bf82969bb90f8628231553
Alors que ce même fichier est toujours requis par l'index.php de l'application. En attendant, le fichier a été rétabli par les ingénieurs du Médialab. Pourquoi a-t-il été supprimé ?

**Comment by paulgirard** [comment]
A votre disposition pour en discuter si besoin.


Le lun. 20 août 2018 11:06, Antoine Trouche <notifications@github.com> a
écrit :

**Comment by tng-KarlFares** [comment]
Bonjour Antoine,

_**les ingénieurs du Medialab ont corrigé des erreurs sur la configuration**_
La modification ne pose aucun problème.


_**il faudrait nous créer une clef d'api du service de cartographie**_
Nous allons vous la créer la clef et nous vous l'enverrons pas e-mail avec les détails associés


_**il y a des fichiers bizarres dans le dossier database/builder qu'il faut corriger**_
En effet le ficher DefaultUpdater.php est une ancienne version de UpdateBuilder.php, nous allons le supprimé du dépôt git.


_**à quoi servent les scripts update_database_v1.php et update_database_v2.php ?**_
Ces fichiers servent à mettre à jour la base de donnée afin d'y ajouter les nouvelles fonctionnalités développées.
Pour simplifier nous les avons réunis dans un seul fichier update_database.php qu'il vous faudra exécuter après l'intallation initiale.


**_la configuration du backoffice a été supprimée par un commit :_**
Du fait d'un différence de configuration entre votre serveur et le notre, nous avons voulu ignorer les différences entre votre version du fichier et la notre. 
En effet la suppression totale du ficher est une erreur de notre part. 
Nous avons créé un fichier commun **_defines.default.php_** celui-ci correspond à **votre version actuelle** du fichier _defines.php_

Ce fichier **_defines.default.php_**: Servira d'exemple afin de mettre à jour votre fichier _defines.php_ le cas échéant.


Bonne journée.

**Comment by paulgirard** [comment]
Ok Merci de ces précisions.

J'attends la nouvelle version pour executer le update_database.
Ça explique des problème que j'avais.
