### ISSUE TITLE
Translate texts of the "install app" button and banner

### ISSUE THREAD

**Issue by boogheta** [medialab/ScienceTrotterS_mobile#85]
@mydu please point to me where to find the text pieces

**Comment by mydu** [comment]
https://github.com/medialab/ScienceTrotterS_mobile/blob/07fd949dc1951bc59ec2cae7d3bdbfa864b7f547/src/assets/i18n/fr.json#L9-L16

https://github.com/medialab/ScienceTrotterS_mobile/blob/07fd949dc1951bc59ec2cae7d3bdbfa864b7f547/src/assets/i18n/fr.json#L9-L16

**Comment by boogheta** [comment]
done, but I'm wondering about the TOAST_MSG_NETWORK with the {{connection}} variable, is the variable internationalized? Otherwise what are its possible values?
