### ISSUE TITLE
[Point d'intérêt page] -  share button is taking too much space inside bibliography 

### ISSUE THREAD

**Issue by mydu** [medialab/ScienceTrotterS_mobile#90]
**Is your feature request related to a problem? Please describe.**
The "share" button is very large and makes the text hard to read

**Describe the solution you'd like**
1. Reduce icon size 
2. OR place it above or below the text

![Screenshot_20201117-191855_Chrome~2](https://user-images.githubusercontent.com/3991275/99522391-de37d900-2995-11eb-9842-61b87b947ad4.jpg)

**Comment by mydu** [comment]
@robindemourat do you have any suggestion?

**Comment by boogheta** [comment]
Maybe it could be moved on the same line as the "Images" title, on the right?
In terms of space it would fit nicely, but I'm not sure it's the right place in terms of sense. But it's not really in a right place now next to the biblio either anyway.

**Comment by robindemourat** [comment]
Hi, +1 to the solution of @boogheta of putting it next to the biblio icon, seems to me it makes sense.

![Capture d’écran 2020-11-18 à 14 28 45](https://user-images.githubusercontent.com/1876890/99536267-6b852880-29aa-11eb-9c85-f6c746c1006c.png)

As an alternative, putting it after the text, on 1 line and as a clear full width button might do the trick imo:

![Capture d’écran 2020-11-18 à 14 25 18](https://user-images.githubusercontent.com/1876890/99536293-72ac3680-29aa-11eb-82ce-9e6f250cdfdd.png)

**Comment by mydu** [comment]
Thank you @robindemourat looks awesome! 
I personally prefer the second one, cause the shared content is only the bibliography not the whole page.

**Comment by boogheta** [comment]
Ah in this case indeed yes. Thanks @robindemourat !

**Comment by boogheta** [comment]
cc @bmaz
