### ISSUE TITLE
Change wording of Vu/Réactiver button

### ISSUE THREAD

**Issue by boogheta** [medialab/ScienceTrotterS_mobile#96]
- [ ] VU (Terminer ce point d'intérêt) -> Marsuer comme vu (Marquer ce point d'intérêt comme vu)
- [x] COMPLETED (End this landmark) -> Mark as completed (Mark this landmark as completed)
- [x] REACTIVER (Réactiver ce point d'intérêt) -> no change
- [x] RESET (Reset this landmark) -> no change

**Comment by boogheta** [comment]
warning @mydy there is a small typo (coming from here, my bad) : Marsuer => Marquer

**Comment by mydu** [comment]
oups yes it's updated!
