### ISSUE TITLE
Improve home French/English buttons 

### ISSUE THREAD

**Issue by boogheta** [medialab/ScienceTrotterS_mobile#97]
- [x] separate language choice and city choice in two sections
- [x] Add a title on top tge language section saying "Display contents available in" / "Montrer les contenus disponibles en" 
- [x] make language button full width

**Comment by mydu** [comment]
it's been deployed on pprd @boogheta 
![sts-pprd medialab sciences-po fr_home(iPhone 6_7_8 Plus)](https://user-images.githubusercontent.com/3991275/100624921-3ff82b80-3324-11eb-815a-06416f90fb50.png)
